name: pokemon_browser
description: Pokemon browser app built with flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^8.1.0
  cached_network_image: ^3.2.2
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^5.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  mockito: ^5.3.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/pokemon-logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "icons/pokeball.png"